[package]
name = "jackcompiler-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "my_module"
path = "src/main.rs"


[dependencies]


#[[test]]
#name = "test_token"
#path = "tests/test_token.rs"